test:
  client_id: santa_elena
  config_file: ''
  created_at: '2026-04-28T23:02:01.416583'
  criticality: media
  execution_mode: on_demand
  python: bash
  retries: 2
  schedule: null
  script_id: test
  script_name: Test
  script_path: /home/hbuddenberg/developments/kharon/airflow_home/scripts_externos/test/test.sh
  tags: []
  timeout: 3600
