"""
Generated DAG for Test
Script ID: test
Client: Arkh-Ur Internal
Execution Mode: scheduled
Generated by Kharōn
"""

from datetime import datetime, timedelta
from airflow import DAG
from operators.kharon_operator import KharonOperator

default_args = {
    'owner': 'arkh-ur',
    'depends_on_past': False,
    'start_date': datetime(2026, 1, 1),
    'email_on_failure': True,
    'email_on_retry': False,
    'retries': 2,
    'retry_delay': timedelta(minutes=5),
}

dag = DAG(
    dag_id='test',
    default_args=default_args,
    description='Test',
    schedule='0 6 * * *',
    tags=['kharon-auto', 'Arkh-Ur Internal'],
    catchup=False,
)

test_task = KharonOperator(
    task_id='execute_test',
    script_path='/home/hbuddenberg/developments/kharon/airflow_home/scripts_externos/test/test.sh',
    script_id='test',
    client_id='Arkh-Ur Internal',
    timeout=3600,
    dag=dag,
)