"""
Generated DAG for 'Test'
Script ID: santa_elena_test
Client: 'santa_elena'
Execution Mode: on_demand
Generated by Kharōn
"""

from datetime import datetime, timedelta
from airflow import DAG
from operators.kharon_operator import KharonOperator

default_args = {
    'owner': 'arkh-ur',
    'depends_on_past': False,
    'start_date': datetime(2026, 1, 1),
    'email_on_failure': True,
    'email_on_retry': False,
    'retries': 2,
    'retry_delay': timedelta(minutes=5),
}

dag = DAG(
    dag_id='santa_elena_test',
    default_args=default_args,
    description='Test',
    schedule=None,
    tags=['kharon-auto', 'client_santa_elena', 'Test'],
    catchup=False,
)

santa_elena_test_task = KharonOperator(
    task_id='execute_santa_elena_test',
    script_path='/home/hbuddenberg/developments/kharon/airflow_home/scripts_externos/test/test.sh',
    script_id='santa_elena_test',
    client_id='santa_elena',
    timeout=3600,
    args=['--config', 'airflow_home/scripts_externos/test/test.sh'],
    dag=dag,
)